const { JSONFileSyncPreset } = require('lowdb/node');
const { v4: uuidv4 } = require('uuid');
const path = require('path');

const db = JSONFileSyncPreset(path.join(__dirname, 'trippilot.json'), {
  users: [],
  trips: [],
  itinerary: [],
  activities: [],
  weather: []
});

db.read();

// Seed activities if empty
if (!db.data.activities || db.data.activities.length === 0) {
  db.data.activities = [
    // === BEIJING ===
    { id: uuidv4(), name: "Forbidden City", name_local: "故宫", city: "Beijing", category: "History", description: "Imperial palace complex — the world's largest palace", duration: "4h", price: "$8", best_time: "8:30am", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "history,architecture,unesco,family,photo" },
    { id: uuidv4(), name: "Great Wall (Mutianyu)", name_local: "慕田峪长城", city: "Beijing", category: "History", description: "Best-preserved section with cable car and toboggan", duration: "5h", price: "$12", best_time: "8:00am", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 10, tags: "history,scenic,hiking,adventure,photo" },
    { id: uuidv4(), name: "Temple of Heaven", name_local: "天坛", city: "Beijing", category: "History", description: "Ming dynasty temple complex with park", duration: "2h", price: "$5", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "history,architecture,park,family" },
    { id: uuidv4(), name: "Summer Palace", name_local: "颐和园", city: "Beijing", category: "History", description: "Imperial garden with Kunming Lake and Longevity Hill", duration: "3h", price: "$6", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "history,nature,photo,relax,family" },
    { id: uuidv4(), name: "798 Art District", name_local: "798艺术区", city: "Beijing", category: "Art", description: "Contemporary art galleries in former factory zone", duration: "3h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 0, teen: 1, photo: 7, tags: "art,modern,shopping,photo" },
    { id: uuidv4(), name: "Hutong Rickshaw Tour", name_local: "胡同", city: "Beijing", category: "Culture", description: "Traditional alleyway tour by rickshaw", duration: "2h", price: "$15", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,history,family,photo" },
    { id: uuidv4(), name: "Beijing Duck at Da Dong", name_local: "大董烤鸭", city: "Beijing", category: "Food", description: "World-famous Peking duck restaurant", duration: "2h", price: "$40", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "food,photo,family,luxury" },
    { id: uuidv4(), name: "Houhai Lake Bar Street", name_local: "后海酒吧街", city: "Beijing", category: "Nightlife", description: "Lakeside bars and live music", duration: "3h", price: "$20", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 0, teen: 0, photo: 6, tags: "nightlife,bar,photo,modern" },

    // === SHANGHAI ===
    { id: uuidv4(), name: "The Bund", name_local: "外滩", city: "Shanghai", category: "Landmark", description: "Historic waterfront with colonial architecture", duration: "2h", price: "Free", best_time: "Sunset", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 10, tags: "views,architecture,night,photo,family" },
    { id: uuidv4(), name: "Oriental Pearl Tower", name_local: "东方明珠", city: "Shanghai", category: "Landmark", description: "Iconic TV tower with observation deck", duration: "2h", price: "$18", best_time: "Afternoon", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "views,architecture,photo,family" },
    { id: uuidv4(), name: "Yu Garden & Bazaar", name_local: "豫园", city: "Shanghai", category: "History", description: "Classical Chinese garden with shopping bazaar", duration: "3h", price: "$5", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "history,shopping,food,photo,family" },
    { id: uuidv4(), name: "French Concession", name_local: "法租界", city: "Shanghai", category: "Culture", description: "Tree-lined streets with cafes and boutiques", duration: "3h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,shopping,food,photo,relax" },
    { id: uuidv4(), name: "Shanghai Disneyland", name_local: "上海迪士尼", city: "Shanghai", category: "Entertainment", description: "Disney theme park with Chinese touches", duration: "8h", price: "$60", best_time: "9:00am", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "family,entertainment,photo,adventure" },
    { id: uuidv4(), name: "Xintiandi", name_local: "新天地", city: "Shanghai", category: "Shopping", description: "Upscale dining and shopping in shikumen houses", duration: "2h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "shopping,food,night,modern,photo" },
    { id: uuidv4(), name: "Shanghai Museum", name_local: "上海博物馆", city: "Shanghai", category: "Museum", description: "Ancient Chinese art and bronze collection", duration: "3h", price: "Free", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 6, tags: "history,art,museum,family" },
    { id: uuidv4(), name: "Tianzifang", name_local: "田子坊", city: "Shanghai", category: "Shopping", description: "Arts and crafts enclave in converted lanes", duration: "2h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "shopping,art,food,photo" },

    // === CHENGDU ===
    { id: uuidv4(), name: "Chengdu Panda Base", name_local: "成都大熊猫繁育研究基地", city: "Chengdu", category: "Wildlife", description: "See giant pandas up close in natural habitat", duration: "3h", price: "$10", best_time: "8:00am", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "wildlife,family,photo,nature" },
    { id: uuidv4(), name: "Jinli Ancient Street", name_local: "锦里古街", city: "Chengdu", category: "Culture", description: "Traditional street food and crafts", duration: "2h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,food,shopping,night" },
    { id: uuidv4(), name: "People's Park Tea House", name_local: "人民公园", city: "Chengdu", category: "Nature", description: "Tea houses and ear cleaning, local life", duration: "2h", price: "$3", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 6, tags: "nature,tea,relax,culture,family" },
    { id: uuidv4(), name: "Mount Qingcheng", name_local: "青城山", city: "Chengdu", category: "Nature", description: "Taoist mountain temples and hiking", duration: "6h", price: "$15", best_time: "8:00am", weather_sensitivity: "High", difficulty: "Moderate", family: 0, teen: 1, photo: 8, tags: "nature,hiking,temples,photo,adventure" },
    { id: uuidv4(), name: "Taikoo Li", name_local: "太古里", city: "Chengdu", category: "Shopping", description: "Luxury shopping district with open-air design", duration: "3h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "shopping,modern,food,photo" },
    { id: uuidv4(), name: "Wide & Narrow Alleys", name_local: "宽窄巷子", city: "Chengdu", category: "Culture", description: "Historic alleyways with Sichuan culture", duration: "2h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,food,shopping,night,photo" },
    { id: uuidv4(), name: "Sichuan Hot Pot", name_local: "四川火锅", city: "Chengdu", category: "Food", description: "Authentic numbing-spicy Sichuan hot pot", duration: "2h", price: "$15", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 0, photo: 8, tags: "food,photo,family,culture" },
    { id: uuidv4(), name: "Leshan Giant Buddha Day Trip", name_local: "乐山大佛", city: "Chengdu", category: "History", description: "World's largest stone Buddha statue", duration: "8h", price: "$25", best_time: "7:00am", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "history,unesco,photo,family,scenic" },

    // === GUANGZHOU ===
    { id: uuidv4(), name: "Canton Tower", name_local: "广州塔", city: "Guangzhou", category: "Landmark", description: "Tallest tower in China with sky walk", duration: "2h", price: "$20", best_time: "Evening", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "views,architecture,night,photo,family" },
    { id: uuidv4(), name: "Shamian Island", name_local: "沙面岛", city: "Guangzhou", category: "Culture", description: "Colonial European architecture on Pearl River", duration: "2h", price: "Free", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,architecture,photo,relax" },
    { id: uuidv4(), name: "Dim Sum at Panxi", name_local: "泮溪酒家", city: "Guangzhou", category: "Food", description: "Traditional Cantonese dim sum garden restaurant", duration: "2h", price: "$12", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "food,culture,photo,family,garden" },
    { id: uuidv4(), name: "Chimelong Safari Park", name_local: "长隆野生动物世界", city: "Guangzhou", category: "Wildlife", description: "Massive safari park with pandas and white tigers", duration: "6h", price: "$35", best_time: "9:00am", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "wildlife,family,photo,adventure" },
    { id: uuidv4(), name: "Chen Clan Ancestral Hall", name_local: "陈家祠", city: "Guangzhou", category: "History", description: "19th-century clan academy with folk art", duration: "2h", price: "$3", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "history,art,architecture,culture" },
    { id: uuidv4(), name: "Pearl River Night Cruise", name_local: "珠江夜游", city: "Guangzhou", category: "Scenic", description: "Night cruise with city lights", duration: "1.5h", price: "$12", best_time: "Evening", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "views,night,photo,family,romantic" },

    // === SHENZHEN ===
    { id: uuidv4(), name: "Window of the World", name_local: "世界之窗", city: "Shenzhen", category: "Entertainment", description: "Miniature replicas of world landmarks", duration: "4h", price: "$18", best_time: "Morning", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "entertainment,family,photo,adventure" },
    { id: uuidv4(), name: "Dafen Oil Painting Village", name_local: "大芬油画村", city: "Shenzhen", category: "Art", description: "Artists' village producing replica paintings", duration: "2h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 6, tags: "art,shopping,culture,photo" },
    { id: uuidv4(), name: "OCT Loft Creative Park", name_local: "华侨城创意园", city: "Shenzhen", category: "Art", description: "Hip creative district with galleries and cafes", duration: "2h", price: "Free", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 0, teen: 1, photo: 7, tags: "art,modern,food,shopping,photo" },
    { id: uuidv4(), name: "Dameisha Beach", name_local: "大梅沙", city: "Shenzhen", category: "Nature", description: "Popular beach with boardwalk and park", duration: "4h", price: "Free", best_time: "Morning", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "nature,beach,relax,photo,family" },

    // === XI'AN ===
    { id: uuidv4(), name: "Terracotta Warriors", name_local: "兵马俑", city: "Xi'an", category: "History", description: "Ancient terracotta army of Qin Shi Huang", duration: "4h", price: "$18", best_time: "8:00am", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 10, tags: "history,unesco,photo,family,architecture" },
    { id: uuidv4(), name: "Ancient City Wall", name_local: "西安城墙", city: "Xi'an", category: "History", description: "Cycling on Ming dynasty city walls", duration: "3h", price: "$10", best_time: "Morning", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 8, tags: "history,scenic,photo,adventure,family" },
    { id: uuidv4(), name: "Muslim Quarter Food Street", name_local: "回民街", city: "Xi'an", category: "Food", description: "Hui Muslim street food and snacks", duration: "2h", price: "$8", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "food,culture,shopping,night,photo" },
    { id: uuidv4(), name: "Giant Wild Goose Pagoda", name_local: "大雁塔", city: "Xi'an", category: "History", description: "Buddhist pagoda with music fountain show", duration: "2h", price: "$5", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "history,architecture,night,photo,family" },
    { id: uuidv4(), name: "Hua Shan Day Trip", name_local: "华山", city: "Xi'an", category: "Nature", description: "Dramatic mountain with plank walks", duration: "8h", price: "$30", best_time: "6:00am", weather_sensitivity: "High", difficulty: "Hard", family: 0, teen: 1, photo: 9, tags: "nature,hiking,adventure,scenic,photo" },

    // === HANGZHOU ===
    { id: uuidv4(), name: "West Lake", name_local: "西湖", city: "Hangzhou", category: "Nature", description: "UNESCO-listed lake with temples and gardens", duration: "4h", price: "Free", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 10, tags: "nature,scenic,photo,family,relax,unesco" },
    { id: uuidv4(), name: "Lingyin Temple", name_local: "灵隐寺", city: "Hangzhou", category: "History", description: "Ancient Buddhist temple in forest grottoes", duration: "3h", price: "$8", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "history,temples,nature,photo,family" },
    { id: uuidv4(), name: "Dragon Well Tea Village", name_local: "龙井村", city: "Hangzhou", category: "Culture", description: "Famous Longjing green tea plantations", duration: "3h", price: "$10", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "culture,nature,food,photo,relax" },
    { id: uuidv4(), name: "Xixi Wetland Park", name_local: "西溪湿地", city: "Hangzhou", category: "Nature", description: "Urban wetland with boat rides", duration: "3h", price: "$12", best_time: "Afternoon", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "nature,relax,photo,family,boat" },

    // === GUILIN ===
    { id: uuidv4(), name: "Li River Cruise", name_local: "漓江", city: "Guilin", category: "Scenic", description: "Famous karst landscape river cruise to Yangshuo", duration: "4h", price: "$25", best_time: "Morning", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 10, tags: "scenic,nature,photo,family,relax,boat" },
    { id: uuidv4(), name: "Reed Flute Cave", name_local: "芦笛岩", city: "Guilin", category: "Nature", description: "Limestone cave with colored lights", duration: "1.5h", price: "$8", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "nature,photo,family" },
    { id: uuidv4(), name: "Elephant Trunk Hill", name_local: "象鼻山", city: "Guilin", category: "Scenic", description: "Iconic hill shaped like an elephant drinking", duration: "1h", price: "$4", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "scenic,photo,family,nature" },
    { id: uuidv4(), name: "Yangshuo Countryside Biking", name_local: "阳朔骑行", city: "Guilin", category: "Adventure", description: "Biking through rice paddies and karst peaks", duration: "4h", price: "$5", best_time: "Morning", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 9, tags: "adventure,nature,scenic,photo,relax" },

    // === ZHANGJIAJIE ===
    { id: uuidv4(), name: "Avatar Mountains (Tianzi)", name_local: "天子山", city: "Zhangjiajie", category: "Nature", description: "Inspiration for Avatar's floating mountains", duration: "5h", price: "$20", best_time: "Morning", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 10, tags: "nature,scenic,photo,adventure,family,unesco" },
    { id: uuidv4(), name: "Glass Skywalk Bridge", name_local: "玻璃桥", city: "Zhangjiajie", category: "Adventure", description: "World's longest glass-bottom bridge", duration: "2h", price: "$15", best_time: "Morning", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "adventure,scenic,photo,family,thrill" },
    { id: uuidv4(), name: "Bailong Elevator", name_local: "百龙天梯", city: "Zhangjiajie", category: "Scenic", description: "World's tallest outdoor elevator on cliff", duration: "1h", price: "$10", best_time: "Morning", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "scenic,photo,views,family" },

    // === SUZHOU ===
    { id: uuidv4(), name: "Humble Administrator's Garden", name_local: "拙政园", city: "Suzhou", category: "History", description: "UNESCO classical Chinese garden masterpiece", duration: "2h", price: "$7", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "history,garden,unesco,photo,relax,family" },
    { id: uuidv4(), name: "Tiger Hill Pagoda", name_local: "虎丘", city: "Suzhou", category: "History", description: "Leaning pagoda on ancient hill with legends", duration: "2h", price: "$5", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "history,architecture,photo,family" },
    { id: uuidv4(), name: "Grand Canal Boat Ride", name_local: "京杭大运河", city: "Suzhou", category: "Scenic", description: "Boat ride on world's longest ancient canal", duration: "1h", price: "$6", best_time: "Afternoon", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "scenic,history,boat,photo,relax" },

    // === HONG KONG ===
    { id: uuidv4(), name: "Victoria Peak", name_local: "太平山顶", city: "Hong Kong", category: "Landmark", description: "Panoramic skyline views from tram summit", duration: "2h", price: "$8", best_time: "Evening", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 10, tags: "views,night,photo,family,scenic" },
    { id: uuidv4(), name: "Tsim Sha Tsui Promenade", name_local: "尖沙咀海滨", city: "Hong Kong", category: "Scenic", description: "Harbour walk with skyline light show", duration: "1.5h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "views,night,photo,family,free" },
    { id: uuidv4(), name: "Dim Sum at Tim Ho Wan", name_local: "添好运", city: "Hong Kong", category: "Food", description: "World's cheapest Michelin-starred dim sum", duration: "1.5h", price: "$10", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "food,photo,family,culture,michelin" },
    { id: uuidv4(), name: "Hong Kong Disneyland", name_local: "香港迪士尼", city: "Hong Kong", category: "Entertainment", description: "Disney theme park with Chinese elements", duration: "8h", price: "$70", best_time: "9:00am", weather_sensitivity: "High", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "entertainment,family,photo,adventure" },
    { id: uuidv4(), name: "Star Ferry", name_local: "天星小轮", city: "Hong Kong", category: "Scenic", description: "Iconic harbour crossing since 1888", duration: "0.5h", price: "$0.5", best_time: "Evening", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "scenic,views,photo,boat,family,cheap" },
    { id: uuidv4(), name: "Temple Street Night Market", name_local: "庙街夜市", city: "Hong Kong", category: "Shopping", description: "Bustling night market with street food", duration: "2h", price: "$10", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "shopping,food,night,photo,culture" },
    { id: uuidv4(), name: "Lamma Island Hike", name_local: "南丫岛", city: "Hong Kong", category: "Nature", description: "Island hiking trail with seafood village", duration: "4h", price: "$3", best_time: "Morning", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 8, tags: "nature,hiking,food,photo,scenic,relax" },

    // === LIJIANG ===
    { id: uuidv4(), name: "Old Town of Lijiang", name_local: "丽江古城", city: "Lijiang", category: "Culture", description: "UNESCO Naxi minority ancient town", duration: "3h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "culture,unesco,photo,night,shopping,family" },
    { id: uuidv4(), name: "Jade Dragon Snow Mountain", name_local: "玉龙雪山", city: "Lijiang", category: "Nature", description: "Sacred snow-capped mountain with glacier", duration: "6h", price: "$25", best_time: "Morning", weather_sensitivity: "High", difficulty: "Moderate", family: 1, teen: 1, photo: 10, tags: "nature,scenic,photo,adventure,family" },
    { id: uuidv4(), name: "Tiger Leaping Gorge", name_local: "虎跳峡", city: "Lijiang", category: "Adventure", description: "One of world's deepest river canyons", duration: "8h", price: "$10", best_time: "Morning", weather_sensitivity: "High", difficulty: "Hard", family: 0, teen: 1, photo: 9, tags: "adventure,nature,hiking,scenic,photo" },

    // === HUANGSHAN ===
    { id: uuidv4(), name: "Yellow Mountain Sunrise", name_local: "黄山日出", city: "Huangshan", category: "Nature", description: "Famous sunrise over sea of clouds", duration: "6h", price: "$25", best_time: "4:00am", weather_sensitivity: "High", difficulty: "Moderate", family: 0, teen: 1, photo: 10, tags: "nature,scenic,photo,adventure,hiking" },
    { id: uuidv4(), name: "Hot Springs Resort", name_local: "黄山温泉", city: "Huangshan", category: "Relax", description: "Natural hot springs after mountain hiking", duration: "3h", price: "$20", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 6, tags: "relax,nature,photo,family" },

    // === NANJING ===
    { id: uuidv4(), name: "Sun Yat-sen Mausoleum", name_local: "中山陵", city: "Nanjing", category: "History", description: "Memorial to founding father of modern China", duration: "2h", price: "Free", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Moderate", family: 1, teen: 1, photo: 7, tags: "history,architecture,photo,family,free" },
    { id: uuidv4(), name: "Confucius Temple", name_local: "夫子庙", city: "Nanjing", category: "History", description: "Temple complex with Qinhuai River snacks", duration: "2h", price: "$5", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 7, tags: "history,culture,food,night,photo,family" },
    { id: uuidv4(), name: "Nanjing Massacre Memorial", name_local: "南京大屠杀纪念馆", city: "Nanjing", category: "Museum", description: "Moving WWII memorial museum", duration: "2h", price: "Free", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 5, tags: "history,museum,family,education" },

    // === CHONGQING ===
    { id: uuidv4(), name: "Hongya Cave", name_local: "洪崖洞", city: "Chongqing", category: "Landmark", description: "Stilted cliffside buildings with night lights", duration: "2h", price: "Free", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "architecture,night,photo,family,views" },
    { id: uuidv4(), name: "Chongqing Hot Pot", name_local: "重庆火锅", city: "Chongqing", description: "Legendary numbing-spicy hot pot by Yangtze", duration: "2h", price: "$12", best_time: "Evening", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 0, photo: 8, tags: "food,culture,photo,family,spicy" },
    { id: uuidv4(), name: "Dazu Rock Carvings", name_local: "大足石刻", city: "Chongqing", category: "History", description: "UNESCO Buddhist rock carvings", duration: "4h", price: "$15", best_time: "Morning", weather_sensitivity: "Low", difficulty: "Easy", family: 1, teen: 1, photo: 8, tags: "history,unesco,art,photo,family" },
    { id: uuidv4(), name: "Yangtze River Cruise", name_local: "长江三峡", city: "Chongqing", category: "Scenic", description: "Three Gorges cruise from Chongqing", duration: "12h", price: "$80", best_time: "Morning", weather_sensitivity: "Medium", difficulty: "Easy", family: 1, teen: 1, photo: 9, tags: "scenic,boat,photo,family,relax,nature" },
  ];
  db.write();
}

module.exports = db;
